name: macOS Compile EAS

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - .github/workflows/macos-compile-test
      - packages/expo-modules-core/e2e/setup/create-eas-project-macos.ts
  push:
    branches: [main, 'sdk-*']
    paths:
      - .github/workflows/macos-compile-test.yml
      - packages/expo/**
      - packages/expo-file-system/**
      - packages/expo-font/**
      - packages/expo-modules-autolinking/**
      - packages/expo-modules-core/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    env:
      UPDATES_PORT: 4747
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v4
      - name: ⬢ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: ➕ Add `bin` to GITHUB_PATH
        run: echo "$(yarn global bin)" >> $GITHUB_PATH
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          yarn-workspace: 'true'
      - name: 🧶 Yarn install
        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: 🔧 Install eas-cli
        run: yarn global add eas-cli
      - name: 🌳 Add EXPO_REPO_ROOT to environment
        run: echo "EXPO_REPO_ROOT=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: 📦 Get artifacts path
        run: mkdir -p artifact && echo "ARTIFACTS_DEST=$(pwd)/artifact" >> $GITHUB_ENV
      - name: 📦 Get commit message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=oneline | head -c1000)" >> $GITHUB_ENV
      - name: 📦 Set test project location
        run: echo "TEST_PROJECT_ROOT=$GITHUB_WORKSPACE/modules-core-e2e" >> $GITHUB_ENV
      - name: 📦 Setup test project for testing MacOS build
        run: yarn --silent ts-node --transpile-only ./packages/expo-modules-core/e2e/setup/create-eas-project-macos.ts
      - name: 🚀 Build with EAS for macOS
        uses: ./.github/actions/eas-build
        id: build_eas
        with:
          platform: 'ios'
          profile: 'testing_debug'
          projectRoot: './modules-core-e2e'
          expoToken: ${{ secrets.EAS_BUILD_BOT_TOKEN }}
          noWait: ${{ github.event.schedule }}
          message: ${{ github.event.pull_request.title }}
      - name: On macOS compile workflow canceled
        if: ${{ cancelled() && steps.build_eas.outputs.build_id }}
        run: eas build:cancel ${{ steps.build_eas.outputs.build_id }}
        working-directory: './modules-core-e2e'
        env:
          EXPO_TOKEN: ${{ secrets.EAS_BUILD_BOT_TOKEN }}
          EAS_BUILD_PROFILE: testing_debug
